export const options = [
    {
        label:'id',
        prop:'id'
    },
    {
        label:'username',
        prop:'username'
    },
    {
        label:'email',
        prop:'email'
    },
    {
        label:'role_name',
        prop:'role_name'
    },
    {
        label:'mg_state',
        prop:'mg_state'
    },
    {
        label:'create_time',
        prop:'create_time'
    },
    {
        label:'action',
        prop:'action',
        width:200
    },
]